[32mINFO    [0m integration.helpers:helpers.py:360 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:312 Retrieving primary unit
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:167 Creating invalid upgrade charm
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:170 Refreshing mysql router with an invalid charm
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:173 Wait for upgrade to fail
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:181 Ensure continuous writes while in failure state
[32mINFO    [0m integration.helpers:helpers.py:360 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:312 Retrieving primary unit
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:184 Re-refresh the charm
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:187 Wait for the charm to be rolled back
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router/0 [idle] active: Router 8.0.41+testupgrade running; Snap rev 121 (outdated); Charmed operator 1+be36621-dirty
  mysql-router/1 [idle] active: Router 8.0.41+testupgrade running; Snap rev 121 (outdated); Charmed operator 1+be36621-dirty
  mysql-router/2 [idle] active: Router 8.0.41+testupgrade running; Snap rev 121 (outdated); Charmed operator 1+be36621-dirty
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router/0 [idle] active: 
  mysql-router/1 [idle] active: 
  mysql-router/2 [idle] active: 
[32mINFO    [0m juju.model:model.py:3211 Waiting for model:
  mysql-router/0 [idle] active: 
  mysql-router/1 [idle] active: 
  mysql-router/2 [idle] active: 
[32mINFO    [0m integration.test_upgrade:test_upgrade.py:203 Ensure continuous writes after rollback procedure
[32mINFO    [0m integration.helpers:helpers.py:360 Ensure continuous writes are incrementing
[32mINFO    [0m integration.helpers:helpers.py:312 Retrieving primary unit
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.7    unsupported  01:52:42Z

App             Version          Status  Scale  Charm           Channel      Rev  Exposed  Message
mysql           8.0.41-0ubun...  active      1  mysql           8.0/edge     376  no       
mysql-router    8.0.41-0ubun...  active      3  mysql-router                   2  no       
mysql-test-app  0.0.2            active      3  mysql-test-app  latest/edge   73  no       

Unit               Workload  Agent  Machine  Public address  Ports           Message
mysql-test-app/0*  active    idle   0        10.154.189.5                    
  mysql-router/0*  active    idle            10.154.189.5                    
mysql-test-app/1   active    idle   1        10.154.189.58                   
  mysql-router/2   active    idle            10.154.189.58                   
mysql-test-app/2   active    idle   2        10.154.189.107                  
  mysql-router/1   active    idle            10.154.189.107                  
mysql/0*           active    idle   3        10.154.189.48   3306,33060/tcp  Primary

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.154.189.5    juju-04f095-0  ubuntu@22.04      Running
1        started  10.154.189.58   juju-04f095-1  ubuntu@22.04      Running
2        started  10.154.189.107  juju-04f095-2  ubuntu@22.04      Running
3        started  10.154.189.48   juju-04f095-3  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-0: 01:42:21 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:42:21 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-0: 01:42:22 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-router-0: 01:42:29 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 2
machine-2: 01:44:14 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:44:14 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-2: 01:44:15 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-router-1: 01:44:19 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-3: 01:44:30 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-3: 01:44:30 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:44:30 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:44:38 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:44:38 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-1: 01:44:39 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-router-2: 01:44:44 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 2
unit-mysql-router-2: 01:48:01 ERROR unit.mysql-router/2.juju-log Unable to connect to MySQL Router
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/src/charm.py", line 154, in wait_until_mysql_router_ready
    for attempt in tenacity.Retrying(
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/src/charm.py", line 174, in wait_until_mysql_router_ready
    assert self._container.path(socket_file).exists()
AssertionError
unit-mysql-router-2: 01:48:01 ERROR unit.mysql-router/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/src/charm.py", line 235, in <module>
    ops.main.main(MachineSubordinateRouterCharm)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 436, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/lib/python3.10/site-packages/ops/main.py", line 144, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 351, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 853, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/lib/python3.10/site-packages/ops/framework.py", line 942, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 738, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/src/abstract_charm.py", line 306, in reconcile
    self._upgrade.upgrade_unit(
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 738, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/src/machine_upgrade.py", line 193, in upgrade_unit
    workload_.upgrade(event=event, unit=self._unit, tls=tls, exporter_config=exporter_config)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 738, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/src/workload.py", line 436, in upgrade
    self._enable_router(event=event, tls=tls, unit_name=unit.name)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 738, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/src/workload.py", line 341, in _enable_router
    self._charm.wait_until_mysql_router_ready(event=event)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 738, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/src/charm.py", line 154, in wait_until_mysql_router_ready
    for attempt in tenacity.Retrying(
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/var/lib/juju/agents/unit-mysql-router-2/charm/src/charm.py", line 174, in wait_until_mysql_router_ready
    assert self._container.path(socket_file).exists()
AssertionError
unit-mysql-router-2: 01:48:01 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...