[32mINFO    [0m integration.test_data_integrator:test_data_integrator.py:102 Ensuring no data exists in the test database
[32mINFO    [0m integration.helpers:helpers.py:468 Running get-credentials on data-integrator/0
[32mINFO    [0m integration.test_data_integrator:test_data_integrator.py:130 Relating mysqlrouter with self-signed-certificates
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m integration.test_data_integrator:test_data_integrator.py:176 Removing relation between mysqlrouter and self-signed-certificates
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.4    unsupported  01:39:05Z

App                       Version          Status  Scale  Charm                     Channel        Rev  Exposed  Message
data-integrator                            active      1  data-integrator           latest/stable   78  no       
mysql                     8.0.41-0ubun...  active      1  mysql                     8.0/edge       370  no       
mysql-router              8.0.41-0ubun...  active      1  mysql-router                               0  no       
self-signed-certificates                   active      1  self-signed-certificates  latest/stable  264  no       

Unit                         Workload  Agent      Machine  Public address  Ports           Message
data-integrator/0*           active    idle       1        10.135.212.71                   
  mysql-router/0*            active    executing           10.135.212.71   6446-6447/tcp   
mysql/0*                     active    idle       0        10.135.212.38   3306,33060/tcp  Primary
self-signed-certificates/0*  active    idle       2        10.135.212.25                   

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.135.212.38  juju-d01b22-0  ubuntu@22.04      Running
1        started  10.135.212.71  juju-d01b22-1  ubuntu@22.04      Running
2        started  10.135.212.25  juju-d01b22-2  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-0: 01:35:56 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:35:56 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:35:56 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-0: 01:37:11 ERROR unit.mysql/0.juju-log ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/snap/charmed-mysql/common/var/run/mysqld/mysqld.sock' (2)
unit-mysql-0: 01:37:11 ERROR unit.mysql/0.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/mysql/v0/mysql.py", line 3363, in check_mysqlcli_connection
    self._run_mysqlcli_script(
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 855, in _run_mysqlcli_script
    raise MySQLClientError
charms.mysql.v0.mysql.MySQLClientError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 860, in _run_mysqlcli_script
    stdout = subprocess.check_output(command, timeout=timeout, text=True)
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysql', '-u', 'root', '-N', '-B', '--socket=/var/snap/charmed-mysql/common/var/run/mysqld/mysqld.sock', '-e', 'SELECT 1']' returned non-zero exit status 1.
unit-mysql-0: 01:37:11 ERROR unit.mysql/0.juju-log Failed to connect to MySQL with mysqlcli with default root user
machine-2: 01:37:18 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-2: 01:37:18 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-self-signed-certificates-0: 01:37:18 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
machine-1: 01:37:20 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:37:20 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-data-integrator-0: 01:37:21 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-router-0: 01:37:26 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...